/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-05-24 07:58:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.paginasjsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gestor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/paginasjsp/../paginasjsp/formCadastroGestor.jsp", Long.valueOf(1400913749930L));
    _jspx_dependants.put("/paginasjsp/../paginasjsp/formCadastroExames.jsp", Long.valueOf(1400914562683L));
    _jspx_dependants.put("/paginasjsp/menu.jsp", Long.valueOf(1400918309365L));
    _jspx_dependants.put("/paginasjsp/../index.html", Long.valueOf(1400917189148L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\" />\r\n");
      out.write("<script src='http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'></script>\r\n");
      out.write("<script type='text/javascript' src=\"menu_jquery.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"estilos.css\"/>\r\n");
      out.write("<title>Hue - Laboratorio Medicinal</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<div id=\"cabecalho\">\r\n");
      out.write("\t<img src=\"images/banner.png\">\r\n");
      out.write("\t</div>   \r\n");
      out.write("\t<div id=\"pagina\">\r\n");
      out.write("\t<div id=\"conteudo\">\r\n");
      out.write("\t<div id=\"imageminicio\">\r\n");
      out.write("\t\t<img src=\"images/imageminicio.png\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<h1>História</h1>\r\n");
      out.write("\t<p><pre>Compromisso com a precisão diagnóstica\r\n");
      out.write("\t\r\n");
      out.write("Confiance Medicina Diagnóstica iniciou suas atividades em 19 de Fevereiro de 2001 com o compromisso de prestar serviços laboratoriais com\r\n");
      out.write("a mais alta qualidade. \r\n");
      out.write("Um diagnóstico correto depende de vários critérios: uma boa avaliação clínica, resultados laboratoriais precisos e confiáveis, além\r\n");
      out.write("de profissionais altamente qualificados.\r\n");
      out.write("\r\n");
      out.write("O Confiance Medicina Diagnóstica realiza exames de análises clínicas plenamente confiáveis porque possui precisão analítica, controle \r\n");
      out.write("constante da qualidade, alta tecnologia, coleta humanizada e acolhedora, além de uma equipe de profissionais com 20 anos de experiência\r\n");
      out.write("e atuação na área de Patologia Clínica - Medicina Laboratorial, que trabalham eficientemente, contribuindo no aprimoramento diagnóstico\r\n");
      out.write("e na promoção da saúde.\r\n");
      out.write("</pre></p>\r\n");
      out.write("\t<h2>Nossa Missão</h2>\r\n");
      out.write("\t<p><pre>\"Realizar com excelência técnica, dentro de princípios rigorosos de ética e humanização, os serviços e procedimentos diagnósticos em Medicina\r\n");
      out.write("Laboratorial, contribuindo para a prevenção de doenças e a promoção da Saúde.\"</pre></p>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<div id=\"rodape\">\r\n");
      out.write("        <address>Hue Lab &copy;2014 <a href=\"mailto: contato@HueLab.com.br\">Contato</a></address>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("<div id='cssmenu'>\r\n");
      out.write("\t<ul>\r\n");
      out.write("   \t\t<li class='active'><a href='index.jsp'><span>Inicio</span></a></li>\r\n");
      out.write("   \t\t<li class='has-sub'><a href='#'><span>Exames</span></a>\r\n");
      out.write("      \t\t<ul>\r\n");
      out.write("         \t\t<li><a href='paginas/biocheck.html'><span>Biocheck up</span></a></li>\r\n");
      out.write("         \t\t<li class='last'><a href='paginas/laboratoriais.html'><span>Laboratoriais</span></a></li>\r\n");
      out.write("      \t\t</ul>\r\n");
      out.write("   \t\t</li>\r\n");
      out.write("   \t\t<li><a href='paginas/coleta.html'><span>Coleta domiciliar</span></a></li>\r\n");
      out.write("   \t\t<li class='last'><a href='paginas/contato.html'><span>Contato</span></a></li>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUsuario.gestor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t<li class=''><a href='paginasjsp/gestor.jsp'><span>Cadastros</span></a></li>\r\n");
      out.write("\t\t\t<li class=''><a href='paginasjsp/gestor.jsp'><span>Cadastro de Exames</span></a></li>\t\t\t\r\n");
      out.write("\t\t</c:if>\r\n");
      out.write("\t</ul>\r\n");
      out.write(" </div>");
      out.write("\r\n");
      out.write("\t<div id=\"wrapper\" class=\"clearfix\">\r\n");
      out.write("\t");
      out.write("<div id=\"formulario\">\r\n");
      out.write("\t<form action=\"cadastroServlet\" method=\"post\">\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msgerro}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<label for=\"nome\">Nome</label> <br /> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tname=\"nome\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.nome}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("' />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<label for=\"rg\">RG</label> <br /> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tname=\"rg\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.rg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("' />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<label for=\"email\">E-mail</label> <br /> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tname=\"email\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("' />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<label for=\"password\">Senha</label> <br /> <input type=\"password\"\r\n");
      out.write("\t\t\t\t\tname=\"password\" />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<label for=\"passwordValida\">Repita a Senha</label> <br /> <input type=\"password\"\r\n");
      out.write("\t\t\t\t\tname=\"passwordValida\" />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Enviar\" />\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("<div id=\"formulario\">\r\n");
      out.write("\t<form action=\"cadastroServlet\" method=\"post\">\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msgerro}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<label for=\"codigo\">Codigo</label> <br /> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tname=\"codigo\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.codigo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("' />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<label for=\"exame\">Exame</label> <br /> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tname=\"exame\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.exame}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("' />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<label for=\"medico\">Medico</label> <br /> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tname=\"medico\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.medico}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("' />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<label for=\"crm_medico\">CRM Medico</label> <br /> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tname=\"crm_medico\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.crm_medico}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("' />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<label for=\"convenio\">Convenio</label> <br /> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tname=\"convenio\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.convenio}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("' />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<label for=\"data_exame\">Data do exame</label> <br /> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tname=\"data_exame\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.data_exame}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("' />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<label for=\"descricao\">Descrição Medica</label> <br /> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tname=\"descricao\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.descricao}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("' />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Enviar\" />\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
