/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-05-26 00:41:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class exames_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/paginas/rodape.html", Long.valueOf(1400920268589L));
    _jspx_dependants.put("/paginas/exames.html", Long.valueOf(1401001479594L));
    _jspx_dependants.put("/paginasjsp/menu.jsp", Long.valueOf(1401064839408L));
    _jspx_dependants.put("/paginas/inicio.html", Long.valueOf(1401003505564L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\" />\r\n");
      out.write("<script src='http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'></script>\r\n");
      out.write("<script type='text/javascript' src=\"menu_jquery.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"estilos.css\"/>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\t<div id=\"cabecalho\">\r\n");
      out.write("\t<img src=\"images/banner.png\">\r\n");
      out.write("\t</div>   \r\n");
      out.write("\t\r\n");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("<div id='cssmenu'>\r\n");
      out.write("\t<ul>\r\n");
      out.write("   \t\t<li class='active'><a href='index.jsp'><span>Inicio</span></a></li>\r\n");
      out.write("   \t\t<li class='has-sub'><a href='exames.jsp'><span>Exames</span></a>\r\n");
      out.write("      \t\t<ul>\r\n");
      out.write("         \t\t<li><a href='biocheck.jsp'><span>Biocheck up</span></a></li>\r\n");
      out.write("         \t\t<li class='last'><a href='laboratoriais.jsp'><span>Laboratoriais</span></a></li>\r\n");
      out.write("      \t\t</ul>\r\n");
      out.write("   \t\t</li>\r\n");
      out.write("   \t\t<li><a href='coleta.jsp'><span>Coleta domiciliar</span></a></li>\r\n");
      out.write("   \t\t<li class='last'><a href='contato.jsp'><span>Contato</span></a></li>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUsuario.gestor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t<li class=''><a href='gestor1.jsp'><span>Cadastros</span></a></li>\r\n");
      out.write("\t\t\t<li class=''><a href='gestor2.jsp'><span>Cadastro de Exames</span></a></li>\t\t\t\r\n");
      out.write("\t\t</c:if>\r\n");
      out.write("\t</ul>\r\n");
      out.write(" </div>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("<div id=\"pagina\">\r\n");
      out.write("\t<div id=\"conteudo\">\r\n");
      out.write("\t<h2>Exames Laboratoriais</h2>\r\n");
      out.write("\t<table style=\"width:750px\">\r\n");
      out.write("\t<colgroup>\r\n");
      out.write("\t\t<col span=\"4\" style=\"background-color:#98FB98;\">\r\n");
      out.write("\t</colgroup>\r\n");
      out.write("       \r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>A</th>\r\n");
      out.write("\t\t\t<th>B</th> \r\n");
      out.write("\t\t\t<th>C</th>\r\n");
      out.write("\t\t\t<th>D</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>ACETONA na URINA</td>\r\n");
      out.write("\t\t\t<td>BIÓPSIA</td> \r\n");
      out.write("\t\t\t<td>CÁDMIO URINA</td>\r\n");
      out.write("\t\t\t<td>DISMORFISMO ERITROCITÁRIO</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>ACIDO HOMOVANILICO</td>\r\n");
      out.write("\t\t\t<td>BRUCELOSE</td> \r\n");
      out.write("\t\t\t<td>CÁLCIO; Ca</td>\r\n");
      out.write("\t\t\t<td>DIGITOXINA</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>ACIDO ÚRICO</td>\r\n");
      out.write("\t\t\t<td>BACTERIOSCOPIA DE FEZES</td> \r\n");
      out.write("\t\t\t<td>CAXUMBA</td>\r\n");
      out.write("\t\t\t<td>DiCLOROMETANO</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>ALDOSTERONA PLASMÁTICA</td>\r\n");
      out.write("\t\t\t<td>BACTERIOSCOPIA DE URINA </td> \r\n");
      out.write("\t\t\t<td>CULTURA DE OROFARINGE</td>\r\n");
      out.write("\t\t\t<td>DHEA</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>E</th>\r\n");
      out.write("\t\t\t<th>F</th> \r\n");
      out.write("\t\t\t<th>G</th>\r\n");
      out.write("\t\t\t<th>H</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>ESPERMOGRAMA</td>\r\n");
      out.write("\t\t\t<td>FENOL URINÁRIO</td> \r\n");
      out.write("\t\t\t<td>GASTRINA</td>\r\n");
      out.write("\t\t\t<td>HIDROXIPROLINA</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>ERITROPOIETINA</td>\r\n");
      out.write("\t\t\t<td>FERRITINA</td> \r\n");
      out.write("\t\t\t<td>GRUPO ABO; Tipo sanguíneo</td>\r\n");
      out.write("\t\t\t<td>HORMÔNIO DE CRESCIMENTO</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>ERITOGRAMA</td>\r\n");
      out.write("\t\t\t<td>FENITOÍNA</td> \r\n");
      out.write("\t\t\t<td>GASOMETRIA</td>\r\n");
      out.write("\t\t\t<td>HAPTOGLOBINA</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>E3; ESTRIOL</td>\r\n");
      out.write("\t\t\t<td>FATOR V (Coagulação)</td> \r\n");
      out.write("\t\t\t<td>GLICOSE JEJUM</td>\r\n");
      out.write("\t\t\t<td>HCV ANTICORPOS</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("<div id=\"rodape\">\r\n");
      out.write("        <address>Hue Lab &copy;2014 <a href=\"mailto: contato@HueLab.com.br\">Contato</a></address>\r\n");
      out.write("\t</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
